import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowLeft, Check, Sparkles, FolderTree, Cpu, ShieldAlert } from 'lucide-react'

export const Route = createFileRoute('/about')({
  component: AboutPage,
})

function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-10">
      {/* Header */}
      <div className="space-y-4">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-cyan-400 hover:text-cyan-300 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          About This Architecture
        </h1>
        <p className="text-slate-400 text-base leading-relaxed">
          This project implements the modern recommended practices for client-side and full-stack React applications,
          eliminating runtime routing errors and manual route map synchronization.
        </p>
      </div>

      {/* Directory Structure Guide */}
      <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4">
        <div className="flex items-center gap-2 text-white font-semibold">
          <FolderTree className="w-5 h-5 text-indigo-400" />
          Project Structure
        </div>
        <div className="bg-slate-950 p-4 rounded-xl font-mono text-xs text-slate-300 overflow-x-auto leading-relaxed border border-slate-800">
          <div>src/</div>
          <div className="pl-4 text-cyan-400">├── components/</div>
          <div className="pl-8 text-slate-400">└── Navbar.tsx <span className="text-slate-600">// Shared top navigation</span></div>
          <div className="pl-4 text-cyan-400">├── routes/</div>
          <div className="pl-8 text-slate-400">├── __root.tsx <span className="text-slate-600">// Root layout route (navbar + outlet + devtools)</span></div>
          <div className="pl-8 text-slate-400">├── index.tsx <span className="text-slate-600">// Home route (/)</span></div>
          <div className="pl-8 text-slate-400">└── about.tsx <span className="text-slate-600">// About route (/about)</span></div>
          <div className="pl-4 text-cyan-400">├── lib/</div>
          <div className="pl-8 text-slate-400">└── utils.ts <span className="text-slate-600">// Styling helpers (cn)</span></div>
          <div className="pl-4 text-slate-400">├── routeTree.gen.ts <span className="text-amber-400">// Automatically generated by TanStack Router</span></div>
          <div className="pl-4 text-slate-400">├── index.css <span className="text-slate-600">// Tailwind CSS v4 styling entry</span></div>
          <div className="pl-4 text-slate-400">└── main.tsx <span className="text-slate-600">// QueryClient & Router initialization</span></div>
        </div>
      </div>

      {/* Benefits checklist */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="p-5 rounded-xl border border-slate-800 bg-slate-900/40 space-y-2">
          <div className="flex items-center gap-2 font-medium text-white">
            <Check className="w-4 h-4 text-emerald-400" />
            Zero-Config Route Generation
          </div>
          <p className="text-xs text-slate-400">
            Adding a file into <code className="text-cyan-300">src/routes</code> generates the route tree and TypeScript definitions automatically on file save.
          </p>
        </div>

        <div className="p-5 rounded-xl border border-slate-800 bg-slate-900/40 space-y-2">
          <div className="flex items-center gap-2 font-medium text-white">
            <Check className="w-4 h-4 text-emerald-400" />
            Automatic Code-Splitting
          </div>
          <p className="text-xs text-slate-400">
            Vite and TanStack Router split your bundle route-by-route so your users only download code when visiting that page.
          </p>
        </div>

        <div className="p-5 rounded-xl border border-slate-800 bg-slate-900/40 space-y-2">
          <div className="flex items-center gap-2 font-medium text-white">
            <Check className="w-4 h-4 text-emerald-400" />
            Stale-While-Revalidate Caching
          </div>
          <p className="text-xs text-slate-400">
            TanStack Query ensures background updates happen transparently with zero layout shift or manual caching code.
          </p>
        </div>

        <div className="p-5 rounded-xl border border-slate-800 bg-slate-900/40 space-y-2">
          <div className="flex items-center gap-2 font-medium text-white">
            <Check className="w-4 h-4 text-emerald-400" />
            Type-Safe Links & Navigations
          </div>
          <p className="text-xs text-slate-400">
            The <code className="text-cyan-300">&lt;Link to="..."&gt;</code> component autocompletes available paths and warns you of dead links at compile-time.
          </p>
        </div>
      </div>
    </div>
  )
}
