/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AeoGeoRouteImport } from './routes/aeo-geo'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as LocalSeoGbpRouteImport } from './routes/local-seo-gbp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as NationalSeoRouteImport } from './routes/national-seo'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SystemsAuditRouteImport } from './routes/systems-audit'
import { Route as SystemsAutoRouteImport } from './routes/systems-auto'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WebsiteDemoRouteImport } from './routes/website-demo'
import { Route as WebsiteDesignRouteImport } from './routes/website-design'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as WebsitesCareRouteImport } from './routes/websites-care'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminWorkspaceRouteImport } from './routes/admin/workspace'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as RShareTokenRouteImport } from './routes/r/$shareToken'
import { Route as SeoIndexRouteImport } from './routes/seo/index'
import { Route as SeoAeoGeoRouteImport } from './routes/seo/aeo-geo'
import { Route as SeoAiSearchRouteImport } from './routes/seo/ai-search'
import { Route as SeoLocalRouteImport } from './routes/seo/local'
import { Route as SeoNationalRouteImport } from './routes/seo/national'
import { Route as SuperadminActivityRouteImport } from './routes/superadmin/activity'
import { Route as WebsitesIndexRouteImport } from './routes/websites/index'
import { Route as WebsitesDesignAndDevelopmentRouteImport } from './routes/websites/design-and-development'
import { Route as WebsitesHostingAndMaintenanceRouteImport } from './routes/websites/hosting-and-maintenance'
import { Route as AdminAgenciesIndexRouteImport } from './routes/admin/agencies/index'
import { Route as AdminAgenciesPartnerIdRouteImport } from './routes/admin/agencies/$partnerId'
import { Route as AdminAgenciesUnassignedRouteImport } from './routes/admin/agencies/unassigned'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin/clients_.$clientId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports/$id'
import { Route as AdminReportsNewRouteImport } from './routes/admin/reports/new'
import { Route as PortalReportsIdRouteImport } from './routes/portal/reports/$id'
import { Route as AdminReportsIdEditRouteImport } from './routes/admin/reports/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoGeoRoute = AeoGeoRouteImport.update({
  id: '/aeo-geo',
  path: '/aeo-geo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSeoGbpRoute = LocalSeoGbpRouteImport.update({
  id: '/local-seo-gbp',
  path: '/local-seo-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalSeoRoute = NationalSeoRouteImport.update({
  id: '/national-seo',
  path: '/national-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsAuditRoute = SystemsAuditRouteImport.update({
  id: '/systems-audit',
  path: '/systems-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsAutoRoute = SystemsAutoRouteImport.update({
  id: '/systems-auto',
  path: '/systems-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDemoRoute = WebsiteDemoRouteImport.update({
  id: '/website-demo',
  path: '/website-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDesignRoute = WebsiteDesignRouteImport.update({
  id: '/website-design',
  path: '/website-design',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesCareRoute = WebsitesCareRouteImport.update({
  id: '/websites-care',
  path: '/websites-care',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspaceRoute = AdminWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const RShareTokenRoute = RShareTokenRouteImport.update({
  id: '/r/$shareToken',
  path: '/r/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoIndexRoute = SeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeoRoute,
} as any)
const SeoAeoGeoRoute = SeoAeoGeoRouteImport.update({
  id: '/aeo-geo',
  path: '/aeo-geo',
  getParentRoute: () => SeoRoute,
} as any)
const SeoAiSearchRoute = SeoAiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => SeoRoute,
} as any)
const SeoLocalRoute = SeoLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => SeoRoute,
} as any)
const SeoNationalRoute = SeoNationalRouteImport.update({
  id: '/national',
  path: '/national',
  getParentRoute: () => SeoRoute,
} as any)
const SuperadminActivityRoute = SuperadminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperadminRoute,
} as any)
const WebsitesIndexRoute = WebsitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsitesRoute,
} as any)
const WebsitesDesignAndDevelopmentRoute =
  WebsitesDesignAndDevelopmentRouteImport.update({
    id: '/design-and-development',
    path: '/design-and-development',
    getParentRoute: () => WebsitesRoute,
  } as any)
const WebsitesHostingAndMaintenanceRoute =
  WebsitesHostingAndMaintenanceRouteImport.update({
    id: '/hosting-and-maintenance',
    path: '/hosting-and-maintenance',
    getParentRoute: () => WebsitesRoute,
  } as any)
const AdminAgenciesIndexRoute = AdminAgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesPartnerIdRoute = AdminAgenciesPartnerIdRouteImport.update({
  id: '/agencies/$partnerId',
  path: '/agencies/$partnerId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesUnassignedRoute = AdminAgenciesUnassignedRouteImport.update({
  id: '/agencies/unassigned',
  path: '/agencies/unassigned',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients_/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsNewRoute = AdminReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AdminRoute,
} as any)
const PortalReportsIdRoute = PortalReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => PortalRoute,
} as any)
const AdminReportsIdEditRoute = AdminReportsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/aeo-geo': typeof AeoGeoRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/local-seo-gbp': typeof LocalSeoGbpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-work': typeof MyWorkRoute
  '/national-seo': typeof NationalSeoRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/seo': typeof SeoRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/systems-audit': typeof SystemsAuditRoute
  '/systems-auto': typeof SystemsAutoRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/website-demo': typeof WebsiteDemoRoute
  '/website-design': typeof WebsiteDesignRoute
  '/websites': typeof WebsitesRouteWithChildren
  '/websites-care': typeof WebsitesCareRoute
  '/work': typeof WorkRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/workspace': typeof AdminWorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$shareToken': typeof RShareTokenRoute
  '/seo/aeo-geo': typeof SeoAeoGeoRoute
  '/seo/ai-search': typeof SeoAiSearchRoute
  '/seo/local': typeof SeoLocalRoute
  '/seo/national': typeof SeoNationalRoute
  '/superadmin/activity': typeof SuperadminActivityRoute
  '/websites/design-and-development': typeof WebsitesDesignAndDevelopmentRoute
  '/websites/hosting-and-maintenance': typeof WebsitesHostingAndMaintenanceRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/seo/': typeof SeoIndexRoute
  '/websites/': typeof WebsitesIndexRoute
  '/admin/agencies/$partnerId': typeof AdminAgenciesPartnerIdRoute
  '/admin/agencies/unassigned': typeof AdminAgenciesUnassignedRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRouteWithChildren
  '/admin/reports/new': typeof AdminReportsNewRoute
  '/portal/reports/$id': typeof PortalReportsIdRoute
  '/admin/agencies/': typeof AdminAgenciesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/reports/$id/edit': typeof AdminReportsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/aeo-geo': typeof AeoGeoRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/local-seo-gbp': typeof LocalSeoGbpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-work': typeof MyWorkRoute
  '/national-seo': typeof NationalSeoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/systems-audit': typeof SystemsAuditRoute
  '/systems-auto': typeof SystemsAutoRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/website-demo': typeof WebsiteDemoRoute
  '/website-design': typeof WebsiteDesignRoute
  '/websites-care': typeof WebsitesCareRoute
  '/work': typeof WorkRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/workspace': typeof AdminWorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$shareToken': typeof RShareTokenRoute
  '/seo/aeo-geo': typeof SeoAeoGeoRoute
  '/seo/ai-search': typeof SeoAiSearchRoute
  '/seo/local': typeof SeoLocalRoute
  '/seo/national': typeof SeoNationalRoute
  '/superadmin/activity': typeof SuperadminActivityRoute
  '/websites/design-and-development': typeof WebsitesDesignAndDevelopmentRoute
  '/websites/hosting-and-maintenance': typeof WebsitesHostingAndMaintenanceRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/portal': typeof PortalIndexRoute
  '/seo': typeof SeoIndexRoute
  '/websites': typeof WebsitesIndexRoute
  '/admin/agencies/$partnerId': typeof AdminAgenciesPartnerIdRoute
  '/admin/agencies/unassigned': typeof AdminAgenciesUnassignedRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRouteWithChildren
  '/admin/reports/new': typeof AdminReportsNewRoute
  '/portal/reports/$id': typeof PortalReportsIdRoute
  '/admin/agencies': typeof AdminAgenciesIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/reports/$id/edit': typeof AdminReportsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/aeo-geo': typeof AeoGeoRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/local-seo-gbp': typeof LocalSeoGbpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-work': typeof MyWorkRoute
  '/national-seo': typeof NationalSeoRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/seo': typeof SeoRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/systems-audit': typeof SystemsAuditRoute
  '/systems-auto': typeof SystemsAutoRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/website-demo': typeof WebsiteDemoRoute
  '/website-design': typeof WebsiteDesignRoute
  '/websites': typeof WebsitesRouteWithChildren
  '/websites-care': typeof WebsitesCareRoute
  '/work': typeof WorkRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/workspace': typeof AdminWorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$shareToken': typeof RShareTokenRoute
  '/seo/aeo-geo': typeof SeoAeoGeoRoute
  '/seo/ai-search': typeof SeoAiSearchRoute
  '/seo/local': typeof SeoLocalRoute
  '/seo/national': typeof SeoNationalRoute
  '/superadmin/activity': typeof SuperadminActivityRoute
  '/websites/design-and-development': typeof WebsitesDesignAndDevelopmentRoute
  '/websites/hosting-and-maintenance': typeof WebsitesHostingAndMaintenanceRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/seo/': typeof SeoIndexRoute
  '/websites/': typeof WebsitesIndexRoute
  '/admin/agencies/$partnerId': typeof AdminAgenciesPartnerIdRoute
  '/admin/agencies/unassigned': typeof AdminAgenciesUnassignedRoute
  '/admin/clients_/$clientId': typeof AdminClientsClientIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRouteWithChildren
  '/admin/reports/new': typeof AdminReportsNewRoute
  '/portal/reports/$id': typeof PortalReportsIdRoute
  '/admin/agencies/': typeof AdminAgenciesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/reports/$id/edit': typeof AdminReportsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/aeo-geo'
    | '/audit'
    | '/contact'
    | '/cookie-policy'
    | '/local-seo-gbp'
    | '/login'
    | '/messages'
    | '/my-work'
    | '/national-seo'
    | '/portal'
    | '/privacy-policy'
    | '/seo'
    | '/superadmin'
    | '/systems-audit'
    | '/systems-auto'
    | '/terms'
    | '/thank-you'
    | '/website-demo'
    | '/website-design'
    | '/websites'
    | '/websites-care'
    | '/work'
    | '/admin/activity'
    | '/admin/clients'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/team'
    | '/admin/workspace'
    | '/blog/$slug'
    | '/r/$shareToken'
    | '/seo/aeo-geo'
    | '/seo/ai-search'
    | '/seo/local'
    | '/seo/national'
    | '/superadmin/activity'
    | '/websites/design-and-development'
    | '/websites/hosting-and-maintenance'
    | '/admin/'
    | '/blog/'
    | '/portal/'
    | '/seo/'
    | '/websites/'
    | '/admin/agencies/$partnerId'
    | '/admin/agencies/unassigned'
    | '/admin/clients/$clientId'
    | '/admin/reports/$id'
    | '/admin/reports/new'
    | '/portal/reports/$id'
    | '/admin/agencies/'
    | '/admin/reports/'
    | '/admin/reports/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/aeo-geo'
    | '/audit'
    | '/contact'
    | '/cookie-policy'
    | '/local-seo-gbp'
    | '/login'
    | '/messages'
    | '/my-work'
    | '/national-seo'
    | '/privacy-policy'
    | '/superadmin'
    | '/systems-audit'
    | '/systems-auto'
    | '/terms'
    | '/thank-you'
    | '/website-demo'
    | '/website-design'
    | '/websites-care'
    | '/work'
    | '/admin/activity'
    | '/admin/clients'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/team'
    | '/admin/workspace'
    | '/blog/$slug'
    | '/r/$shareToken'
    | '/seo/aeo-geo'
    | '/seo/ai-search'
    | '/seo/local'
    | '/seo/national'
    | '/superadmin/activity'
    | '/websites/design-and-development'
    | '/websites/hosting-and-maintenance'
    | '/admin'
    | '/blog'
    | '/portal'
    | '/seo'
    | '/websites'
    | '/admin/agencies/$partnerId'
    | '/admin/agencies/unassigned'
    | '/admin/clients/$clientId'
    | '/admin/reports/$id'
    | '/admin/reports/new'
    | '/portal/reports/$id'
    | '/admin/agencies'
    | '/admin/reports'
    | '/admin/reports/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/aeo-geo'
    | '/audit'
    | '/contact'
    | '/cookie-policy'
    | '/local-seo-gbp'
    | '/login'
    | '/messages'
    | '/my-work'
    | '/national-seo'
    | '/portal'
    | '/privacy-policy'
    | '/seo'
    | '/superadmin'
    | '/systems-audit'
    | '/systems-auto'
    | '/terms'
    | '/thank-you'
    | '/website-demo'
    | '/website-design'
    | '/websites'
    | '/websites-care'
    | '/work'
    | '/admin/activity'
    | '/admin/clients'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/team'
    | '/admin/workspace'
    | '/blog/$slug'
    | '/r/$shareToken'
    | '/seo/aeo-geo'
    | '/seo/ai-search'
    | '/seo/local'
    | '/seo/national'
    | '/superadmin/activity'
    | '/websites/design-and-development'
    | '/websites/hosting-and-maintenance'
    | '/admin/'
    | '/blog/'
    | '/portal/'
    | '/seo/'
    | '/websites/'
    | '/admin/agencies/$partnerId'
    | '/admin/agencies/unassigned'
    | '/admin/clients_/$clientId'
    | '/admin/reports/$id'
    | '/admin/reports/new'
    | '/portal/reports/$id'
    | '/admin/agencies/'
    | '/admin/reports/'
    | '/admin/reports/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AeoGeoRoute: typeof AeoGeoRoute
  AuditRoute: typeof AuditRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  LocalSeoGbpRoute: typeof LocalSeoGbpRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyWorkRoute: typeof MyWorkRoute
  NationalSeoRoute: typeof NationalSeoRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SeoRoute: typeof SeoRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  SystemsAuditRoute: typeof SystemsAuditRoute
  SystemsAutoRoute: typeof SystemsAutoRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WebsiteDemoRoute: typeof WebsiteDemoRoute
  WebsiteDesignRoute: typeof WebsiteDesignRoute
  WebsitesRoute: typeof WebsitesRouteWithChildren
  WebsitesCareRoute: typeof WebsitesCareRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RShareTokenRoute: typeof RShareTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-geo': {
      id: '/aeo-geo'
      path: '/aeo-geo'
      fullPath: '/aeo-geo'
      preLoaderRoute: typeof AeoGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-seo-gbp': {
      id: '/local-seo-gbp'
      path: '/local-seo-gbp'
      fullPath: '/local-seo-gbp'
      preLoaderRoute: typeof LocalSeoGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-seo': {
      id: '/national-seo'
      path: '/national-seo'
      fullPath: '/national-seo'
      preLoaderRoute: typeof NationalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems-audit': {
      id: '/systems-audit'
      path: '/systems-audit'
      fullPath: '/systems-audit'
      preLoaderRoute: typeof SystemsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems-auto': {
      id: '/systems-auto'
      path: '/systems-auto'
      fullPath: '/systems-auto'
      preLoaderRoute: typeof SystemsAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-demo': {
      id: '/website-demo'
      path: '/website-demo'
      fullPath: '/website-demo'
      preLoaderRoute: typeof WebsiteDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design': {
      id: '/website-design'
      path: '/website-design'
      fullPath: '/website-design'
      preLoaderRoute: typeof WebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites-care': {
      id: '/websites-care'
      path: '/websites-care'
      fullPath: '/websites-care'
      preLoaderRoute: typeof WebsitesCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspace': {
      id: '/admin/workspace'
      path: '/workspace'
      fullPath: '/admin/workspace'
      preLoaderRoute: typeof AdminWorkspaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/r/$shareToken': {
      id: '/r/$shareToken'
      path: '/r/$shareToken'
      fullPath: '/r/$shareToken'
      preLoaderRoute: typeof RShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/': {
      id: '/seo/'
      path: '/'
      fullPath: '/seo/'
      preLoaderRoute: typeof SeoIndexRouteImport
      parentRoute: typeof SeoRoute
    }
    '/seo/aeo-geo': {
      id: '/seo/aeo-geo'
      path: '/aeo-geo'
      fullPath: '/seo/aeo-geo'
      preLoaderRoute: typeof SeoAeoGeoRouteImport
      parentRoute: typeof SeoRoute
    }
    '/seo/ai-search': {
      id: '/seo/ai-search'
      path: '/ai-search'
      fullPath: '/seo/ai-search'
      preLoaderRoute: typeof SeoAiSearchRouteImport
      parentRoute: typeof SeoRoute
    }
    '/seo/local': {
      id: '/seo/local'
      path: '/local'
      fullPath: '/seo/local'
      preLoaderRoute: typeof SeoLocalRouteImport
      parentRoute: typeof SeoRoute
    }
    '/seo/national': {
      id: '/seo/national'
      path: '/national'
      fullPath: '/seo/national'
      preLoaderRoute: typeof SeoNationalRouteImport
      parentRoute: typeof SeoRoute
    }
    '/superadmin/activity': {
      id: '/superadmin/activity'
      path: '/activity'
      fullPath: '/superadmin/activity'
      preLoaderRoute: typeof SuperadminActivityRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/websites/': {
      id: '/websites/'
      path: '/'
      fullPath: '/websites/'
      preLoaderRoute: typeof WebsitesIndexRouteImport
      parentRoute: typeof WebsitesRoute
    }
    '/websites/design-and-development': {
      id: '/websites/design-and-development'
      path: '/design-and-development'
      fullPath: '/websites/design-and-development'
      preLoaderRoute: typeof WebsitesDesignAndDevelopmentRouteImport
      parentRoute: typeof WebsitesRoute
    }
    '/websites/hosting-and-maintenance': {
      id: '/websites/hosting-and-maintenance'
      path: '/hosting-and-maintenance'
      fullPath: '/websites/hosting-and-maintenance'
      preLoaderRoute: typeof WebsitesHostingAndMaintenanceRouteImport
      parentRoute: typeof WebsitesRoute
    }
    '/admin/agencies/': {
      id: '/admin/agencies/'
      path: '/agencies'
      fullPath: '/admin/agencies/'
      preLoaderRoute: typeof AdminAgenciesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies/$partnerId': {
      id: '/admin/agencies/$partnerId'
      path: '/agencies/$partnerId'
      fullPath: '/admin/agencies/$partnerId'
      preLoaderRoute: typeof AdminAgenciesPartnerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies/unassigned': {
      id: '/admin/agencies/unassigned'
      path: '/agencies/unassigned'
      fullPath: '/admin/agencies/unassigned'
      preLoaderRoute: typeof AdminAgenciesUnassignedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients_/$clientId': {
      id: '/admin/clients_/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/new': {
      id: '/admin/reports/new'
      path: '/reports/new'
      fullPath: '/admin/reports/new'
      preLoaderRoute: typeof AdminReportsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/reports/$id': {
      id: '/portal/reports/$id'
      path: '/reports/$id'
      fullPath: '/portal/reports/$id'
      preLoaderRoute: typeof PortalReportsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/reports/$id/edit': {
      id: '/admin/reports/$id/edit'
      path: '/edit'
      fullPath: '/admin/reports/$id/edit'
      preLoaderRoute: typeof AdminReportsIdEditRouteImport
      parentRoute: typeof AdminReportsIdRoute
    }
  }
}

interface AdminReportsIdRouteChildren {
  AdminReportsIdEditRoute: typeof AdminReportsIdEditRoute
}

const AdminReportsIdRouteChildren: AdminReportsIdRouteChildren = {
  AdminReportsIdEditRoute: AdminReportsIdEditRoute,
}

const AdminReportsIdRouteWithChildren = AdminReportsIdRoute._addFileChildren(
  AdminReportsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminWorkspaceRoute: typeof AdminWorkspaceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgenciesPartnerIdRoute: typeof AdminAgenciesPartnerIdRoute
  AdminAgenciesUnassignedRoute: typeof AdminAgenciesUnassignedRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminReportsIdRoute: typeof AdminReportsIdRouteWithChildren
  AdminReportsNewRoute: typeof AdminReportsNewRoute
  AdminAgenciesIndexRoute: typeof AdminAgenciesIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminWorkspaceRoute: AdminWorkspaceRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAgenciesPartnerIdRoute: AdminAgenciesPartnerIdRoute,
  AdminAgenciesUnassignedRoute: AdminAgenciesUnassignedRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminReportsIdRoute: AdminReportsIdRouteWithChildren,
  AdminReportsNewRoute: AdminReportsNewRoute,
  AdminAgenciesIndexRoute: AdminAgenciesIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalReportsIdRoute: typeof PortalReportsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalReportsIdRoute: PortalReportsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SeoRouteChildren {
  SeoAeoGeoRoute: typeof SeoAeoGeoRoute
  SeoAiSearchRoute: typeof SeoAiSearchRoute
  SeoLocalRoute: typeof SeoLocalRoute
  SeoNationalRoute: typeof SeoNationalRoute
  SeoIndexRoute: typeof SeoIndexRoute
}

const SeoRouteChildren: SeoRouteChildren = {
  SeoAeoGeoRoute: SeoAeoGeoRoute,
  SeoAiSearchRoute: SeoAiSearchRoute,
  SeoLocalRoute: SeoLocalRoute,
  SeoNationalRoute: SeoNationalRoute,
  SeoIndexRoute: SeoIndexRoute,
}

const SeoRouteWithChildren = SeoRoute._addFileChildren(SeoRouteChildren)

interface SuperadminRouteChildren {
  SuperadminActivityRoute: typeof SuperadminActivityRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminActivityRoute: SuperadminActivityRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface WebsitesRouteChildren {
  WebsitesDesignAndDevelopmentRoute: typeof WebsitesDesignAndDevelopmentRoute
  WebsitesHostingAndMaintenanceRoute: typeof WebsitesHostingAndMaintenanceRoute
  WebsitesIndexRoute: typeof WebsitesIndexRoute
}

const WebsitesRouteChildren: WebsitesRouteChildren = {
  WebsitesDesignAndDevelopmentRoute: WebsitesDesignAndDevelopmentRoute,
  WebsitesHostingAndMaintenanceRoute: WebsitesHostingAndMaintenanceRoute,
  WebsitesIndexRoute: WebsitesIndexRoute,
}

const WebsitesRouteWithChildren = WebsitesRoute._addFileChildren(
  WebsitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AeoGeoRoute: AeoGeoRoute,
  AuditRoute: AuditRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  LocalSeoGbpRoute: LocalSeoGbpRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyWorkRoute: MyWorkRoute,
  NationalSeoRoute: NationalSeoRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SeoRoute: SeoRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  SystemsAuditRoute: SystemsAuditRoute,
  SystemsAutoRoute: SystemsAutoRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WebsiteDemoRoute: WebsiteDemoRoute,
  WebsiteDesignRoute: WebsiteDesignRoute,
  WebsitesRoute: WebsitesRouteWithChildren,
  WebsitesCareRoute: WebsitesCareRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  RShareTokenRoute: RShareTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
