/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as LocalSeoGbpRouteImport } from './routes/local-seo-gbp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SystemsAutoRouteImport } from './routes/systems-auto'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WebsitesCareRouteImport } from './routes/websites-care'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports/$id'
import { Route as AdminReportsNewRouteImport } from './routes/admin/reports/new'
import { Route as PortalReportsIdRouteImport } from './routes/portal/reports/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSeoGbpRoute = LocalSeoGbpRouteImport.update({
  id: '/local-seo-gbp',
  path: '/local-seo-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsAutoRoute = SystemsAutoRouteImport.update({
  id: '/systems-auto',
  path: '/systems-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesCareRoute = WebsitesCareRouteImport.update({
  id: '/websites-care',
  path: '/websites-care',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsNewRoute = AdminReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AdminRoute,
} as any)
const PortalReportsIdRoute = PortalReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/local-seo-gbp': typeof LocalSeoGbpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/systems-auto': typeof SystemsAutoRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/websites-care': typeof WebsitesCareRoute
  '/work': typeof WorkRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/reports/new': typeof AdminReportsNewRoute
  '/portal/reports/$id': typeof PortalReportsIdRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/local-seo-gbp': typeof LocalSeoGbpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/systems-auto': typeof SystemsAutoRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/websites-care': typeof WebsitesCareRoute
  '/work': typeof WorkRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/reports/new': typeof AdminReportsNewRoute
  '/portal/reports/$id': typeof PortalReportsIdRoute
  '/admin/reports': typeof AdminReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/local-seo-gbp': typeof LocalSeoGbpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/systems-auto': typeof SystemsAutoRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/websites-care': typeof WebsitesCareRoute
  '/work': typeof WorkRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/reports/new': typeof AdminReportsNewRoute
  '/portal/reports/$id': typeof PortalReportsIdRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/audit'
    | '/contact'
    | '/cookie-policy'
    | '/local-seo-gbp'
    | '/login'
    | '/messages'
    | '/portal'
    | '/privacy-policy'
    | '/systems-auto'
    | '/terms'
    | '/thank-you'
    | '/websites-care'
    | '/work'
    | '/admin/clients'
    | '/admin/media'
    | '/admin/posts'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/portal/'
    | '/admin/reports/$id'
    | '/admin/reports/new'
    | '/portal/reports/$id'
    | '/admin/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/audit'
    | '/contact'
    | '/cookie-policy'
    | '/local-seo-gbp'
    | '/login'
    | '/messages'
    | '/privacy-policy'
    | '/systems-auto'
    | '/terms'
    | '/thank-you'
    | '/websites-care'
    | '/work'
    | '/admin/clients'
    | '/admin/media'
    | '/admin/posts'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/portal'
    | '/admin/reports/$id'
    | '/admin/reports/new'
    | '/portal/reports/$id'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/audit'
    | '/contact'
    | '/cookie-policy'
    | '/local-seo-gbp'
    | '/login'
    | '/messages'
    | '/portal'
    | '/privacy-policy'
    | '/systems-auto'
    | '/terms'
    | '/thank-you'
    | '/websites-care'
    | '/work'
    | '/admin/clients'
    | '/admin/media'
    | '/admin/posts'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/portal/'
    | '/admin/reports/$id'
    | '/admin/reports/new'
    | '/portal/reports/$id'
    | '/admin/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuditRoute: typeof AuditRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  LocalSeoGbpRoute: typeof LocalSeoGbpRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SystemsAutoRoute: typeof SystemsAutoRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WebsitesCareRoute: typeof WebsitesCareRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-seo-gbp': {
      id: '/local-seo-gbp'
      path: '/local-seo-gbp'
      fullPath: '/local-seo-gbp'
      preLoaderRoute: typeof LocalSeoGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems-auto': {
      id: '/systems-auto'
      path: '/systems-auto'
      fullPath: '/systems-auto'
      preLoaderRoute: typeof SystemsAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites-care': {
      id: '/websites-care'
      path: '/websites-care'
      fullPath: '/websites-care'
      preLoaderRoute: typeof WebsitesCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/new': {
      id: '/admin/reports/new'
      path: '/reports/new'
      fullPath: '/admin/reports/new'
      preLoaderRoute: typeof AdminReportsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/reports/$id': {
      id: '/portal/reports/$id'
      path: '/reports/$id'
      fullPath: '/portal/reports/$id'
      preLoaderRoute: typeof PortalReportsIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  AdminReportsNewRoute: typeof AdminReportsNewRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  AdminReportsNewRoute: AdminReportsNewRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalReportsIdRoute: typeof PortalReportsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalReportsIdRoute: PortalReportsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuditRoute: AuditRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  LocalSeoGbpRoute: LocalSeoGbpRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SystemsAutoRoute: SystemsAutoRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WebsitesCareRoute: WebsitesCareRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
